name-template: "v$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
    - title: "🚀 Features"
      labels:
          - "enhancement"
    - title: "🐛 Bug Fixes"
      labels:
          - "bug"
    - title: "🧰 Maintenance"
      labels:
          - "documentation"
          - "refactor"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
    major:
        labels:
            - "major"
    minor:
        labels:
            - "minor"
    patch:
        labels:
            - "patch"
    default: patch
template: |
    ## Changes This Version

    $CHANGES
